apiVersion: v1
kind: ConfigMap
metadata:
  name: accord-web-nginx-config
  namespace: accord
data:
  default.conf: |
    server {
      listen 0.0.0.0:4200;
      server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
      }
    }