---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accord-service
  name: accord-service
  namespace: accord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accord-service
  template:
    metadata:
      labels:
        app: accord-service
    spec:
      containers:
        - image: quay.io/accord/accord-service:latest
          name: accord-service
          imagePullPolicy: Always
          env:
          envFrom:
          - configMapRef:
              name: accord-service-configmap 
          volumeMounts:
            - name: accord-service-connections-json
              mountPath: /etc/private/accord
      volumes:
        - name: accord-service-connections-json
          configMap:
            name: accord-service-connections-json
        - name: accord-service-mongo-connections-configmap
          configMap:
            name: accord-service-mongo-connections-configmap
