kind: ConfigMap
apiVersion: v1
metadata:
  name: accord-service-configmap
  namespace: accord
data:
   BUILD_ENV: "prod"
   REDIS_ENV_HOST: "accord-service-redis-service"
   PODLIB_NAMESPACE: "accord"
   PODLIB_INCLUSTER: "true"
   PODLIB_CONFIG: "userpod"
   CONNECTIONS_JSON: | 
      {"ENV": "prod", "MONGODB": {"HOSTS":["mongo"], "PORT":"27017", "CLIENT_ID":"accord_user", "CLIENT_SECRET":"accord_pass"}, "INCOMMON_SSO": {"HOSTS": [""], "PORT":"", "CLIENT_ID":"", "CLIENT_SECRET":""}}
