apiVersion: v1
kind: ConfigMap
metadata:
  name: accord-service-nginx-config
  namespace: accord
data:
  default: |
    server {
        listen 0.0.0.0:5000;
        server_name localhost;

        # max upload size
        client_max_body_size 75M;
    
        # underscores_in_headers on;

        location / {
            # proxy_pass_request_headers on;
            # include proxy_params;
            # proxy_set_header eppn $HTTP_EPPN;
            # proxy_set_header sn $HTTP_SN;
            # proxy_set_header givenName $HTTP_GIVENNAME;
            # proxy_set_header displayName $HTTP_DISPLAYNAME;
            # proxy_set_header cn $HTTP_CN;
            # proxy_set_header affiliation $HTTP_UNSCOPED_AFFILIATION;
            # proxy_set_header uid $HTTP_UID;
            # proxy_set_header email $HTTP_EPPN;
            # proxy_set_header title $HTTP_TITLE;
            # proxy_pass http://unix:///ithriv_service/app.sock;

            include uwsgi_params;
            uwsgi_param eppn $HTTP_EPPN;
            uwsgi_param sn $HTTP_SN;
            uwsgi_param givenName $HTTP_GIVENNAME;
            uwsgi_param displayName $HTTP_DISPLAYNAME;
            uwsgi_param cn $HTTP_CN;
            uwsgi_param affiliation $HTTP_UNSCOPED_AFFILIATION;
            uwsgi_param uid $HTTP_UID;
            uwsgi_param gid $HTTP_GID;
            uwsgi_param email $HTTP_EPPN;
            uwsgi_param title $HTTP_TITLE;
            uwsgi_param entitlement $HTTP_ENTITLEMENT;
            uwsgi_param targetedID $HTTP_TARGETED_ID;
            uwsgi_param persistentID $HTTP_PERSISTENT_ID;
            uwsgi_param isMemberOf $HTTP_ISMEMBEROF;
            uwsgi_param telephoneNumber $HTTP_TELEPHONENUMBER;
            uwsgi_param initials $HTTP_INITIALS;
            uwsgi_param description $HTTP_DESCRIPTION;
            uwsgi_param carLicense $HTTP_CARLICENSE;
            uwsgi_param departmentNumber $HTTP_DEPARTMENTNUMBER;
            uwsgi_param employeeNumber $HTTP_EMPLOYEENUMBER;
            uwsgi_param employeeType $HTTP_EMPLOYEETYPE;
            uwsgi_param preferencialLanguage $HTTP_PREFERREDLANGUAGE;
            uwsgi_param manager $HTTP_MANAGER;
            uwsgi_param seealSO $HTTP_SEEALSO;
            uwsgi_param fax $HTTP_FACSIMILETELEPHONENUMBER;
            uwsgi_param street $HTTP_STREET;
            uwsgi_param pobox $HTTP_POSTOFFICEBOX;
            uwsgi_param pc $HTTP_POSTALCODE;
            uwsgi_param st $HTTP_ST;
            uwsgi_param l $HTTP_L;
            uwsgi_param o $HTTP_O;
            uwsgi_param ou $HTTP_OU;
            uwsgi_param businessCategory $HTTP_BUSINESSCATEGORY;
            uwsgi_param physicalDeliveryOfficeName $HTTP_PHYSICALDELIVERYOFFICENAME;
            uwsgi_pass unix:///accord_service/app.sock;
        }
    }