---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
#  volumeMode: Filesystem
#  volumeName: pvc-prom-grafana-0
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
